# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microtvm_device/microDevice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!microtvm_device/microDevice.proto\x12\x0bmicroDevice\"Z\n\rDeviceMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x16\n\x0esession_number\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\"a\n\x0b\x44\x65viceReply\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x10\n\x08is_alive\x18\x02 \x01(\x08\x12\x0b\n\x03vid\x18\x03 \x01(\t\x12\x0b\n\x03pid\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\"6\n\x0eSessionMessage\x12\x16\n\x0esession_number\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\"\x1d\n\rStringMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2\xdb\x05\n\nRPCRequest\x12J\n\x10RPCDeviceRequest\x12\x1a.microDevice.DeviceMessage\x1a\x18.microDevice.DeviceReply\"\x00\x12J\n\x10RPCDeviceRelease\x12\x1a.microDevice.DeviceMessage\x1a\x18.microDevice.DeviceReply\"\x00\x12J\n\x10RPCDeviceIsAlive\x12\x1a.microDevice.DeviceMessage\x1a\x18.microDevice.DeviceReply\"\x00\x12O\n\x11RPCSessionRequest\x12\x1b.microDevice.SessionMessage\x1a\x1b.microDevice.SessionMessage\"\x00\x12M\n\x0fRPCSessionClose\x12\x1b.microDevice.SessionMessage\x1a\x1b.microDevice.SessionMessage\"\x00\x12P\n\x14RPCDeviceRequestList\x12\x1a.microDevice.StringMessage\x1a\x1a.microDevice.StringMessage\"\x00\x12R\n\x16RPCDeviceRequestEnable\x12\x1a.microDevice.DeviceMessage\x1a\x1a.microDevice.StringMessage\"\x00\x12S\n\x17RPCDeviceRequestDisable\x12\x1a.microDevice.DeviceMessage\x1a\x1a.microDevice.StringMessage\"\x00\x12N\n\x14RPCGetDeviceTypeInfo\x12\x1a.microDevice.DeviceMessage\x1a\x18.microDevice.DeviceReply\"\x00\x42\x1b\x42\x10MicroDeviceProtoP\x01\xa2\x02\x04MDevb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microtvm_device.microDevice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\020MicroDeviceProtoP\001\242\002\004MDev'
  _DEVICEMESSAGE._serialized_start=50
  _DEVICEMESSAGE._serialized_end=140
  _DEVICEREPLY._serialized_start=142
  _DEVICEREPLY._serialized_end=239
  _SESSIONMESSAGE._serialized_start=241
  _SESSIONMESSAGE._serialized_end=295
  _STRINGMESSAGE._serialized_start=297
  _STRINGMESSAGE._serialized_end=326
  _RPCREQUEST._serialized_start=329
  _RPCREQUEST._serialized_end=1060
# @@protoc_insertion_point(module_scope)
